In [1]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_csv("netflix_titles.csv")
df = df.head(2000)

In [5]:
df

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...
...,...,...,...,...,...,...,...,...,...,...,...,...
1995,s1996,Movie,The Devil All The Time,Antonio Campos,"Tom Holland, Bill Skarsgård, Riley Keough, Rob...",United States,"September 16, 2020",2020,R,139 min,"Dramas, Thrillers",Sinister characters converge around a young ma...
1996,s1997,Movie,The Paramedic,Carles Torras,"Mario Casas, Déborah François, Guillermo Pfeni...",Spain,"September 16, 2020",2020,TV-MA,94 min,"Dramas, International Movies, Thrillers",Unable to face his new reality in a wheelchair...
1997,s1998,Movie,The Take,James Watkins,"Idris Elba, Richard Madden, Charlotte Le Bon, ...","United Kingdom, France, United States, Belgium...","September 16, 2020",2016,R,92 min,"Action & Adventure, International Movies","After a mix-up lands him in hot water, a skill..."
1998,s1999,TV Show,Call the Midwife,Philippa Lowthorpe,"Vanessa Redgrave, Bryony Hannah, Helen George,...",United Kingdom,"September 15, 2020",2020,TV-MA,9 Seasons,"British TV Shows, International TV Shows, TV D...",This period drama set in impoverished East Lon...
1999,s2000,Movie,Hope Frozen: A Quest to Live Twice,Pailin Wedel,NaN,"Thailand, United States","September 15, 2020",2020,TV-PG,80 min,"Documentaries, International Movies",A Thai scientist and his family decide to cryo...

In [7]:
df.drop_duplicates(inplace=True)

In [14]:
df['date_added'] = pd.to_datetime(df['date_added'], errors='coerce')

In [9]:
df['country'].fillna("Unknown", inplace=True)

C:\Users\Shruti\AppData\Local\Temp\ipykernel_22552\3206245367.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['country'].fillna("Unknown", inplace=True)

In [15]:
df.isnull().sum()

show_id         0
type            0
title           0
director        0
cast            0
country         0
date_added      0
release_year    0
rating          0
duration        0
listed_in       0
description     0
dtype: int64

In [11]:
df['director'].fillna("Unknown",inplace = True)

C:\Users\Shruti\AppData\Local\Temp\ipykernel_22552\920115892.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['director'].fillna("Unknown",inplace = True)

In [12]:
df['cast'].fillna("Unknown", inplace = True)

C:\Users\Shruti\AppData\Local\Temp\ipykernel_22552\2275272973.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['cast'].fillna("Unknown", inplace = True)

In [16]:
df['duration'] = df['duration'].astype(str)

In [17]:
df['country'] = df['country'].str.strip()

In [18]:
df['director'] = df['director'].str.strip()

In [19]:
df['title'] = df['title'].str.strip()

In [20]:
df.shape

(2000, 12)

In [21]:
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,Unknown,United States,2021-09-25,2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,Unknown,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,2021-09-24,2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",Unknown,2021-09-24,2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,Unknown,Unknown,Unknown,2021-09-24,2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,Unknown,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,2021-09-24,2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

In [22]:
df.to_csv("cleaned_netflix.csv", index=False)

In [23]:
df.shape

(2000, 12)